### PR TITLE
Update full adder

### PR DESCRIPTION
**Pull request by uncomputable**
Implement full adders based on xor and the majority function.

### CODE REVIEW

**Comment by roconnor-blockstream** [comment]
There is a build error.
```
File "./Simplicity/SHA256.v", line 463, characters 0-11:
Error: Unable to unify
 "[218%Z; 16%Z; 240%Z; 232%Z; 83%Z; 6%Z; 149%Z; 208%Z; 117%Z; 100%Z; 240%Z;
  179%Z; 47%Z; 238%Z; 190%Z; 119%Z; 38%Z; 90%Z; 29%Z; 105%Z; 207%Z; 128%Z;
  46%Z; 34%Z; 215%Z; 114%Z; 137%Z; 218%Z; 246%Z; 100%Z; 27%Z; 141%Z]" with
 "[161%Z; 35%Z; 225%Z; 192%Z; 84%Z; 233%Z; 29%Z; 216%Z; 235%Z; 198%Z; 145%Z;
  102%Z; 102%Z; 33%Z; 220%Z; 182%Z; 205%Z; 145%Z; 97%Z; 142%Z; 73%Z; 210%Z;
  160%Z; 109%Z; 143%Z; 202%Z; 112%Z; 154%Z; 13%Z; 112%Z; 105%Z; 82%Z]".
```

The value in SHA256.v needs to be updates.

**Comment by uncomputable** [comment]
Got it. Thanks for double-checking. I will rebuild the library on my end and fix all errors.

**Comment by roconnor-blockstream** [comment]
```
ghci> identityRoot Simplicity.Programs.Sha256.Lib.hashBlock
0xdfc927d39bf7147a8b0a7f4379466870824db102090a00362923a377a91af681
```

This is what the identity root ought to be.  Seems something else needs updating.  I'll investigate.

**Comment by roconnor-blockstream** [comment]
If you are willing, I'd like you to make a few other changes:

* Replace `Fixpoint zero {n : nat} {A} {term : Core.Algebra} : term A (Word n) :=` with `Fixpoint zero {n : nat} {term : Core.Algebra} : term Unit (Word n) :=`

* In multiplier, replace ` iden &&& (zero &&& zero) >>> fullMultiplier` with ` iden &&& (unit >>> zero) >>> fullMultiplier.` (the `zero &&& zero` was actually surpurfulous because just a single `zero` ought to correctly infer the width; however if that doesn't work you can try `(unit >>> zero &&& zero)`.)

* Make similar replacements if there are other type errors.  Refer to the Haskell implementations if necessary.

Let's see if we can get hashBlock's IMR to match.

**Comment by uncomputable** [comment]
The whole shifting and rotation logic needs to be updated. This changed in 722f174 for Haskell. I will try to replicate the functions in Coq, but proving correctness will be tricky.

**Comment by uncomputable** [comment]
The changes required to match Coq's Hashblock CMR with Haskell's exceed the scope of this PR. Let's merge this PR for now with a working intermediate CMR. I will look into updating Coq's shifting and rotation logic.

**Pull request merged**
