### PR TITLE
Implementing disconnect

### PR DESCRIPTION
**Pull request by roconnor-blockstream**
Examples that exercise 'disconnect' will follow this PR (unless the reviewer demands otherwise).

### CODE REVIEW

**Comment by apoelstra** [comment]
I feel a bit weird about using `SIZE_MAX` as a limit in consensus code. Woudn't it be better to use `2^31-1` or something? Realistically we are never going to have 2 billion of anything in a program that can be executed in a blockchain context.

**Comment by roconnor-blockstream** [comment]
Indeed that is why I have

    /* :TODO: replace this check with a consensus critical limit. */

Perhaps you would prefer that I file a github issue to make the issue more prominent?

**Comment by apoelstra** [comment]
Yes please :)

**Comment by roconnor-blockstream** [comment]
This has now been noted as part of issue https://github.com/ElementsProject/simplicity/issues/54.

**Comment by apoelstra** [comment]
Also verified a bunch of calculations in section 6.1 of the TR, as per Russell's request

**Pull request merged**
